accepted = [
	"Apache-2.0",
	"BSD-3-Clause",
	"ISC",
	"MIT",
	"MPL-2.0",
	"OpenSSL",
	"Unicode-DFS-2016",
]
no-clearly-defined = true

[obscuravpn-api]
accepted = ["PolyForm-Noncommercial-1.0.0"]

[ring.clarify]
license = "ISC AND MIT AND OpenSSL"
