accepted = [
	"Apache-2.0",
	"BSD-3-Clause",
	"CDLA-Permissive-2.0",
	"ISC",
	"MIT",
	"MPL-2.0",
	"OpenSSL",
	"Unicode-3.0",
	"Unicode-DFS-2016",
]
no-clearly-defined = true

[obscuravpn-api]
# Our current version of cargo-about doesn't support "GPL-3.0-only"
accepted = ["GPL-3.0 WITH GPL-3.0-linking-source-exception"]

[ring.clarify]
license = "ISC AND MIT AND OpenSSL"
